### ISSUE TITLE
Feature Suggestion: GraphQL API

### ISSUE THREAD

**Issue by janosh** [materialsproject/api#181]
Admittedly, this is a big one but have you considered building a **[GraphQL](https://graphql.org) API for Materials Project**?

There's been a massive shift away from REST APIs and towards GraphQL in the web development community. And for good reasons. Besides being a great fit for this project naming-wise (bad joke, I admit):

- GraphQL allows for more granular and data-efficient queries.
- It has excellent tools for defining types and schemas.
- It makes evolving an API (e.g. field deprecations) easier.
- And, most importantly, it offers a great user experience thanks to tools like [GraphiQL](https://github.com/graphql/graphiql) which allow consumers of the API to explore its schema and investigate the returned data in real time.

In my experience, the latter is excellent for iteratively constructing complex queries. You really have to experience it for yourself to see how intuitive and fun it is.

I'd be willing to help significantly if there's interest. Also, if you haven't heard of GraphQL before, there's a good [official tutorial](https://graphql.org/learn).

**Comment by mkhorton** [comment]
Hi @janosh, thanks for your feedback. We've had discussions about this internally.

We're open to GraphQL but our main concerns are in terms of difficulty in optimizing server load and creating new bottlenecks (both in terms of development time and in terms of performance).

Ultimately we're a fairly small team and adopting a GraphQL would be more than just getting the technology itself to work, but in terms of if we can support and maintain it over the long term, and the time required for everyone to become familiar with how to use it, and then writing documentation, etc. We already have a backlog of high-priority features so we can't commit to adopting it in the near future, though of course offers of help are greatly appreciated.

We're currently working on modernizing our API so that it has a modern, OpenAPI-compliant spec (see [https://api.materialsproject.org/docs](https://api.materialsproject.org/docs)), and we're working on updated Python clients to consume this, which is our near-term priority, along with ensuring that queries are performant and that we're reliably able to supply large blobs over the API (e.g. band structures, charge densities, etc.) in a cost-effective manner.

Thanks for opening this issue though, we welcome further discussion on this, maybe some others in the team have thoughts too.

**Comment by janosh** [comment]
@mkhorton Thanks for the thoughtful reply. I certainly understand your concerns. Setting up a GraphQL endpoint would definitely be a lot of work both due to the learning curve and the actual development effort.

From my experience though, I don't think it's more effort to maintain. And I expect it would actually require less documentation than the REST API. One of the cool things about GraphiQL is that (to some extent) it auto-documents the API based on its schema as can be seen in the right-hand-side of this screenshot:

![graphiql](https://user-images.githubusercontent.com/30958850/104099707-322bb380-529d-11eb-893a-f875188314cb.jpg)
_Source: https://github.com/graphql/graphiql_

Happy to answer further questions if any. Otherwise we could pick it up again once the backlog situation relaxes.

**Comment by mkhorton** [comment]
Thanks for the comments. I'm familiar with GraphQL and its advantages in a general sense, but perhaps it would be useful to ask what specific tasks you might want to accomplish with Materials Project data that wouldn't be possible with our REST API that GraphQL would help with? i.e. what's causing you or your colleagues headaches right now?

If you are volunteering time, I would say our new API uses `FastAPI` which supports GraphQL via `graphene`, but we would not want to write new `graphene` schemas, we would need to re-use our existing `pydantic` document models, so that the documents retrievable via the REST API are broadly consistent with the documents retrievable via GraphQL. I don't have sufficient experience with `graphene` to know how best to do this myself. If you have server-side Python experience we'd definitely be open to a PR to explore/prototype what it could look like, but this is not a small effort.

**Comment by janosh** [comment]
The "main pain point" (this sounds worse than it is, MP is one of the best APIs maintained by scientists I've seen so far 👍) is the time it takes to write queries. Finding the right filters and how to apply them. This is where GraphiQL could speed things up a lot.

An example of efficiency: Yesterday, I was trying to filter results by space group. Due to being a dictionary, it's not possible to filter by any of its keys, in particular not its number (correct me if I'm wrong). So I had to query a lot more data than strictly necessary and then do the filtering locally. I'm not saying this is impossible with a REST API, it's also a question of how the data is stored on the server, but such granular queries, drilling down into nested properties and filtering by them is where GraphQL really shines.

I do have Python experience but not a lot in the context of servers. Mostly been using `node` for that. But I'm always happy to learn new things. :)

There appears to be an actively maintained Pydantic integration for Graphene: https://github.com/graphql-python/graphene-pydantic. Perhaps we could use that to reduce the workload.

**Comment by mkhorton** [comment]
> Due to being a dictionary, it's not possible to filter by any of its keys, in particular not its number (correct me if I'm wrong)

In the current API, this is actually possible, e.g. you could write:

```
with MPRester() as mpr:
    docs = mpr.query({"spacegroup.number":225}, ["material_id", "structure"])
```

to return a list of dictionaries with keys `material_id` and `structure` that matches that spacegroup, using the field name from our [mapidoc](https://github.com/materialsproject/mapidoc/tree/master/materials).

However, this is essentially just doing a MongoDB query on our server side, the `mapidoc` can sometimes become out of date (this system pre-dates a lot of the more modern API conventions), and it's possible to write queries that are very painful from a server or database load perspective. All this to say that filtering on spacegroup will still be possible on the new in-development API, but the exact syntax will likely change.

**Comment by mkhorton** [comment]
Also thanks for the kind words :-)

**Comment by janosh** [comment]
> Also thanks for the kind words :-)

You bet! Thanks for all the hard work you're putting into supporting the materials science community.

And thanks for showing me how to filter by space group. Works great!

**Comment by janosh** [comment]
@mkhorton Related question: Is there an easy way (like a pymatgen function) that maps the space group number to its Bravais lattice?

**Comment by mkhorton** [comment]
The reported values are being taken via from `spglib`, which we rely on to do the heavy lifting for detection of symmetry, subject to a certain tolerance.

You could use:

```
from pymatgen.symmetry.groups import SpaceGroup
system = SpaceGroup.from_int_number(225).crystal_system
print(system)  # "cubic"
```

Note this will only give 7 distinct values if you're interested in crystal *system*, I'm not sure why the API queries are listing the centering too, I'm not familiar with that aspect of the code and would have to look into it.

> Presumably because 2 pairs in this list have isomorphic symmetry groups and are considered the same Bravais lattice?

Yes, I believe `orthorhombicA` and `orthorhombicC` etc are equivalent, it's just a different choice of A vs C for the centering.

**Comment by mkhorton** [comment]
Closing this for now to keep our issues list clean but not against re-opening if new information becomes available.
