### ISSUE TITLE
exclude_elements error

### ISSUE THREAD

**Issue by sean-mcsherry** [materialsproject/api#602]
Hi all,

Nice work on the newer API, I really like the materials search query. However, I found that the exclude_elements field in the summary search is not working properly (I think). It works when you pass a single element. However, if you pass a list of multiple elements, it stops working correctly.

Thanks! 

`from mp_api import MPRester
import numpy as np
import pandas as pd

MAPI_KEY = ''
mpr = MPRester(MAPI_KEY)

#elements_to_avoid = ['H', 'Be','Na','Li', 'K']. #this does not work
elements_to_avoid = ['Li'] # this works

data = mpr.summary.search(exclude_elements = elements_to_avoid, 
                          elements = ['O'], 
                          nelements = [3],
                          is_stable = True,
                          fields =['material_id',
                                   'formula_pretty',
                                   'symmetry.crystal_system',
                                   'symmetry.point_group'])`

**Comment by munrojm** [comment]
Hi @sean-mcsherry, thanks very much for bringing this to our attention. I will investigate and patch release.

**Comment by munrojm** [comment]
Hi @sean-mcsherry, it appears this is due to a documentation mismatch with the current api client. If you use the `search_summary_docs` instead of `search` with your input it should work. Additionally, you can continue using `search` and instead of passing a list, pass a comma delimited string `exclude_elements="Li,O"`. Very soon, all of the `search_***` methods will be gone, and `search` will replace them.

**Comment by munrojm** [comment]
This mismatch is resolved as of the latest release `v0.24.0`.
